### ISSUE TITLE
[Linked Mod Submission Request] [AlternativeTitles]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#1]
**Mod Name (Must match Name key in Manifest.ini):**
Alternative Titles

**Mod ID (Must be alphanumeric, no whitespace):**
AlternativeTitles

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**
https://files.zariteis.de/roguelands/mods/AlternativeTitles/modinfo.ini

**Comment by SuperKael** [comment]
Accepted and linked to the repository!
