### ISSUE TITLE
[Linked Mod Submission Request]

### ISSUE THREAD

**Issue by AqlisZRT** [SuperKael/Roguelands-Mods#10]
**Mod Name (Must match Name key in Manifest.ini):**

**Mod ID (Must be alphanumeric, no whitespace):**

**Any other comments, requests, or questions related to your mod:**

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**

**Comment by Jdewi12** [comment]
Looks like you didn't actually fill out the information.

**Comment by SuperKael** [comment]
Indeed. You did not fill out any information. If you wish to submit a mod, make sure to do so.
