### ISSUE TITLE
[Linked Mod Submission Request] [StorageExpansion]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#11]
**Mod Name (Must match Name key in Manifest.ini):**
Storage Expansion

**Mod ID (Must be alphanumeric, no whitespace):**
StorageExpansion

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/StorageExpansion/modinfo.ini

**Comment by SuperKael** [comment]
Accepted. Feel free to ping me on Discord if I fail to respond to a submission request in a timely manner in the future.
