### ISSUE TITLE
[Linked Mod Submission Request] [StasisPod]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#12]
**Mod Name (Must match Name key in Manifest.ini):**
Stasis Pod

**Mod ID (Must be alphanumeric, no whitespace):**
StasisPod

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/StasisPod/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
