### ISSUE TITLE
[Linked Mod Submission Request] [EnginesDeluxe]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#13]
**Mod Name (Must match Name key in Manifest.ini):**
Engines Deluxe

**Mod ID (Must be alphanumeric, no whitespace):**
EnginesDeluxe

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/EnginesDeluxe/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
