### ISSUE TITLE
[Linked Mod Submission Request] [IronmanChest]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#14]
**Mod Name (Must match Name key in Manifest.ini):**
Ironman Chest

**Mod ID (Must be alphanumeric, no whitespace):**
IronmanChest

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/IronmanChest/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
