### ISSUE TITLE
[Linked Mod Submission Request] [VanitySlots]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#15]
**Mod Name (Must match Name key in Manifest.ini):**
Vanity Slots

**Mod ID (Must be alphanumeric, no whitespace):**
VanitySlots

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/VanitySlots/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
