### ISSUE TITLE
[Linked Mod Submission Request] [OriginalVanityItems]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#16]
**Mod Name (Must match Name key in Manifest.ini):**
Original Vanity Items

**Mod ID (Must be alphanumeric, no whitespace):**
OriginalVanityItems

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/OriginalVanityItems/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
