### ISSUE TITLE
[Local Mod Submission Request]

### ISSUE THREAD

**Issue by Lutcikaur** [SuperKael/Roguelands-Mods#17]
**Mod Name (Must match Name key in Manifest.ini):**
AoEChipFixes

**Mod ID (Must be alphanumeric, no whitespace):**
aoechipfixes

**Mod Version:**
1.0

**Mod GadgetCore Version:**
2.0.3.9

**Mod Description:**
Fixes Darkfire, Photon Blade, and Megaslash.
Recasting while active will reset to max duration.

**Any other properties you would like listed on your Mod Browser page:**

**Any other comments, requests, or questions related to your mod:**

**Mod File (Provide a link to download, or Drag & Drop):**
[AoEChipFixes_v1.0.zip](https://github.com/SuperKael/Roguelands-Mods/files/6527407/AoEChipFixes_v1.0.zip)

**Comment by SuperKael** [comment]
Accepted
