### ISSUE TITLE
[Mod Update Request]

### ISSUE THREAD

**Issue by Lutcikaur** [SuperKael/Roguelands-Mods#18]
**Mod Name (May be changed, must match Name key in Manifest.ini):**
BuffChipFixes

**Mod ID (Must not be changed, Must be alphanumeric, no whitespace):**
aoechipfixes

**Mod Version:**
1.1

**Mod GadgetCore Version:**
2.0.3.9

**Mod Description (Only if different):**

**Any other properties you would like listed or changed on your Mod Browser page:**

**Any other comments, requests, or questions related to your mod:**
Renamed from AoEChipFixes to BuffChipFixes after noticing other similar issues.
[BuffChipFixes_v1.1.zip](https://github.com/SuperKael/Roguelands-Mods/files/6528631/BuffChipFixes_v1.1.zip)

**Mod File (Provide a link to download, or Drag & Drop):**

**Comment by SuperKael** [comment]
Accepted
