### ISSUE TITLE
[Linked Mod Submission Request] [Subworlds]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#19]
**Mod Name (Must match Name key in Manifest.ini):**
Subworlds

**Mod ID (Must be alphanumeric, no whitespace):**
Subworlds

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/Subworlds/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
