### ISSUE TITLE
[Linked Mod Submission Request] [SplashTexts]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#2]
**Mod Name (Must match Name key in Manifest.ini):**
Splash Texts

**Mod ID (Must be alphanumeric, no whitespace):**
SplashTexts

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**
https://files.zariteis.de/roguelands/mods/SplashTexts/modinfo.ini

**Comment by SuperKael** [comment]
Accepted and linked to the repository!
