### ISSUE TITLE
[Linked Mod Submission Request] [MoreVanityItems]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#20]
**Mod Name (Must match Name key in Manifest.ini):**
More Vanity Items

**Mod ID (Must be alphanumeric, no whitespace):**
MoreVanityItems

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/MoreVanityItems/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
