### ISSUE TITLE
[Linked Mod Submission Request] [MultiplayerPlayerStatus]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#21]
**Mod Name (Must match Name key in Manifest.ini):**
Multiplayer Player Status

**Mod ID (Must be alphanumeric, no whitespace):**
MultiplayerPlayerStatus

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/MultiplayerPlayerStatus/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
