### ISSUE TITLE
[Linked Mod Submission Request] [CrystalCrevasse]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#22]
**Mod Name (Must match Name key in Manifest.ini):**
Crystal Crevasse

**Mod ID (Must be alphanumeric, no whitespace):**
CrystalCrevasse

**Any other comments, requests, or questions related to your mod:**
collaboration between @Saewin and me

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/CrystalCrevasse/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
