### ISSUE TITLE
[Linked Mod Submission Request] [UltimateNPCWeapons]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#24]
**Mod Name (Must match Name key in Manifest.ini):**
Ultimate NPC Weapons

**Mod ID (Must be alphanumeric, no whitespace):**
UltimateNPCWeapons

**Any other comments, requests, or questions related to your mod:**
collaboration between @saewin and me

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/UltimateNPCWeapons/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
