### ISSUE TITLE
[Linked Mod Submission Request] [MonsterNests]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#25]
**Mod Name (Must match Name key in Manifest.ini):**
Monster Nests

**Mod ID (Must be alphanumeric, no whitespace):**
MonsterNests

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/MonsterNests/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
