### ISSUE TITLE
[Linked Mod Submission Request] [ScreenshotMode]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#26]
**Mod Name (Must match Name key in Manifest.ini):**
Screenshot Mode

**Mod ID (Must be alphanumeric, no whitespace):**
ScreenshotMode

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/ScreenshotMode/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
