### ISSUE TITLE
AutoSaveMod

### ISSUE THREAD

**Issue by LindaMosep** [SuperKael/Roguelands-Mods#27]
**Mod Name (Must match Name key in Manifest.ini):** AutoSaveMod

**Mod ID (Must be alphanumeric, no whitespace):** AutoSaveMod

**Mod Version:** 1.0

**Mod GadgetCore Version:** 2.0.5.2

**Mod Description:**  AutoSave System for Roguelands.

**Any other properties you would like listed on your Mod Browser page:** Zariteis

**Any other comments, requests, or questions related to your mod:** <3

**Mod File (Provide a link to download, or Drag & Drop):** 
[AutoSaveMod_v1.0.zip](https://github.com/SuperKael/Roguelands-Mods/files/7521506/AutoSaveMod_v1.0.zip)

**Comment by SuperKael** [comment]
Accepted
