### ISSUE TITLE
[Linked Mod Submission Request] [Dresser]

### ISSUE THREAD

**Issue by Jdewi12** [SuperKael/Roguelands-Mods#28]
**Mod Name (Must match Name key in Manifest.ini):**
Dresser

**Mod ID (Must be alphanumeric, no whitespace):**
Dresser

**Any other comments, requests, or questions related to your mod:**
Repo is empty.

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://github.com/Jdewi12/Roguelands-Dresser/releases

**Comment by SuperKael** [comment]
Accepted
