### ISSUE TITLE
[Linked Mod Submission Request] [ServerBrowser]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#29]
**Mod Name (Must match Name key in Manifest.ini):**
Server Browser

**Mod ID (Must be alphanumeric, no whitespace):**
ServerBrowser

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://files.zariteis.de/roguelands/mods/ServerBrowser/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
