### ISSUE TITLE
[Bulk Linked Mod Submission Request] [CombatChipChest;ItemLevelExtension;LoopPortal;MoreLights;MultiplayerClientSpawn;PlatformBlock;QuickStack;RecipeMenuCore;ShadowOne;UltimateRings]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#3]
**Mod Entries:**

CombatChipChest=Name:Combat Chip Chests,URL:https://files.zariteis.de/roguelands/mods/CombatChipChest/modinfo.ini
ItemLevelExtension=Name:Item Level Extension,URL:https://files.zariteis.de/roguelands/mods/ItemLevelExtension/modinfo.ini
LoopPortal=Name:Loop Portal,URL:https://files.zariteis.de/roguelands/mods/LoopPortal/modinfo.ini
MoreLights=Name:More Lights,URL:https://files.zariteis.de/roguelands/mods/MoreLights/modinfo.ini
MultiplayerClientSpawn=Name:Multiplayer Client Spawn,URL:https://files.zariteis.de/roguelands/mods/MultiplayerClientSpawn/modinfo.ini
PlatformBlock=Name:Platform Block,URL:https://files.zariteis.de/roguelands/mods/PlatformBlock/modinfo.ini
QuickStack=Name:Quick Stack,URL:https://files.zariteis.de/roguelands/mods/QuickStack/modinfo.ini
RecipeMenuCore=Name:Recipe Menu Core,URL:https://files.zariteis.de/roguelands/mods/RecipeMenuCore/modinfo.ini
ShadowOne=Name:Shadow One,URL:https://files.zariteis.de/roguelands/mods/ShadowOne/modinfo.ini
UltimateRings=Name:Ultimate Rings,URL:https://files.zariteis.de/roguelands/mods/UltimateRings/modinfo.ini

**Comment by SuperKael** [comment]
Accepted

**Comment by SuperKael** [comment]
Accepted
