### ISSUE TITLE
[Local Mod Submission Request]

### ISSUE THREAD

**Issue by fanfAnRogue** [SuperKael/Roguelands-Mods#30]
**Mod Name (Must match Name key in Manifest.ini):**
Extra Potions

**Mod ID (Must be alphanumeric, no whitespace):**
ffextrapotions

**Mod Version:**
1.0.0.0

**Mod GadgetCore Version:**
2.0.6.6

**Mod Description:**
Add Anti-All potion, Hispd potion and Dblstat potion.

**Any other properties you would like listed on your Mod Browser page:**

**Any other comments, requests, or questions related to your mod:**

**Mod File (Provide a link to download, or Drag & Drop):**

[ExtraPotions_v1.0.zip](https://github.com/SuperKael/Roguelands-Mods/files/9986924/ExtraPotions_v1.0.zip)

**Comment by SuperKael** [comment]
Accepted
