### ISSUE TITLE
[Linked Mod Submission Request]

### ISSUE THREAD

**Issue by Aureuix** [SuperKael/Roguelands-Mods#31]
**Mod Name (Must match Name key in Manifest.ini):**
Armor Tweaks

**Mod ID (Must be alphanumeric, no whitespace):**
ArmorTweaks

**Any other comments, requests, or questions related to your mod:**

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://github.com/Aureuix/RoguelandsArmorTweaks

**Comment by SuperKael** [comment]
Accepted. Next time, please leave the template intact :)
