### ISSUE TITLE
[Linked Mod Submission Request] [GearSwap]

### ISSUE THREAD

**Issue by Jdewi12** [SuperKael/Roguelands-Mods#34]
**Mod Name (Must match Name key in Manifest.ini):**
GearSwap

**Mod ID (Must be alphanumeric, no whitespace):**
GearSwap

**Any other comments, requests, or questions related to your mod:**

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):**
https://github.com/Jdewi12/Roguelands-GearSwap/releases

**Comment by SuperKael** [comment]
Accepted
