### ISSUE TITLE
[Linked Mod Submission Request]

### ISSUE THREAD

**Issue by Aureuix** [SuperKael/Roguelands-Mods#36]
**Mod Name (Must match Name key in Manifest.ini):** Planetary Races

**Mod ID (Must be alphanumeric, no whitespace):** PlanetaryRaces

**Any other comments, requests, or questions related to your mod:**

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page):** https://github.com/Aureuix/RoguelandsPlanetaryRaces

**Comment by SuperKael** [comment]
Accepted
