### ISSUE TITLE
[Linked Mod Submission Request]

### ISSUE THREAD

**Issue by TCsnowkit** [SuperKael/Roguelands-Mods#4]
Tiers+

TiersPlus

**Any other comments, requests, or questions related to your mod:**

https://github.com/TCsnowkit/Tiers_Plus/releases

**Comment by SuperKael** [comment]
Denied - You are not using the GitHub Releases system correctly. You need to upload the release as an "Attached binary", not simply as a link in the text area.

**Comment by SuperKael** [comment]
Feel free to submit another request once you have correct your release.
