### ISSUE TITLE
[Linked Mod Submission Request] [AncientReassembler]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#6]
**Mod Name (Must match Name key in Manifest.ini):**
Ancient Reassembler

**Mod ID (Must be alphanumeric, no whitespace):**
AncientReassembler

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**
https://files.zariteis.de/roguelands/mods/AncientReassembler/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
