### ISSUE TITLE
[Linked Mod Submission Request] [ScrapYard]

### ISSUE THREAD

**Issue by Zariteis** [SuperKael/Roguelands-Mods#8]
**Mod Name (Must match Name key in Manifest.ini):**
Scrap Yard

**Mod ID (Must be alphanumeric, no whitespace):**
ScrapYard

**Any other comments, requests, or questions related to your mod:**
none

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**
https://files.zariteis.de/roguelands/mods/ScrapYard/modinfo.ini

**Comment by SuperKael** [comment]
Accepted
