### ISSUE TITLE
[Bulk Linked Mod Submission Request] [BetterItemHoming;AggroOnHit;MultiplayerScaling;NoBlackBars;Minimap;PermanentNuldmg;ItemFrames;ManaRegenRework;HealthRegenRework]

### ISSUE THREAD

**Issue by Jdewi12** [SuperKael/Roguelands-Mods#9]
**Mod Name (Must match Name key in Manifest.ini):**
BetterItemHoming
AggroOnHit
MultiplayerScaling
NoBlackBars
Minimap
PermanentNuldmg
ItemFrames
ManaRegenRework
HealthRegenRework

**Mod ID (Must be alphanumeric, no whitespace):**
BetterItemHoming
AggroOnHit
MultiplayerScaling
NoBlackBars
Minimap
PermanentNuldmg
ItemFrames
ManaRegenRework
HealthRegenRework

**Any other comments, requests, or questions related to your mod:**
Many of the repos are empty and the ones that aren't don't necessarily match the releases.

**Mod URL (Must link to an ini file that provides information about your mod, or a GitHub releases page)**
https://github.com/Jdewi12/Roguelands-BetterItemHoming/releases
https://github.com/Jdewi12/Roguelands-AggroOnHit/releases
https://github.com/Jdewi12/Roguelands-MultiplayerScaling/releases
https://github.com/Jdewi12/Roguelands-NoBlackBars/releases
https://github.com/Jdewi12/Roguelands-Minimap/releases
https://github.com/Jdewi12/Roguelands-PermanentNuldmg/releases
https://github.com/Jdewi12/Roguelands-ItemFrames/releases
https://github.com/Jdewi12/Roguelands-ManaRegenRework/releases
https://github.com/Jdewi12/Roguelands-HealthRegenRework/releases

**Comment by SuperKael** [comment]
Accepted
